examples: fix sysrepoctl.py --list
Fix the following error:

  $ ./examples/sysrepoctl.py --list
  Traceback (most recent call last):
    File "./examples/sysrepoctl.py", line 46, in <module>
      for module in conn.get_ly_ctx():
  TypeError: '_GeneratorContextManager' object is not iterable

The libyang context must be acquired.

Fixes: 2cf79848c05f ("Port to libyang2/sysrepo2")
Signed-off-by: Robin Jarry <robin@jarry.cc>