subscription: remove notification callback return value
Fix the following CFFI error:

 From cffi callback <function event_notif_tree_callback>:
 Trying to convert the result back to C:
 TypeError: callback with the return type 'void' must return None

Do not return anything and avoid sending the error to the sysrepo
session.

Fixes: #18
Fixes: 382a07cc8e35 ("subscription: fix async notifications callbacks")
Signed-off-by: Robin Jarry <robin@jarry.cc>