cffi: fix install when SYSREPO_HEADERS is not set
When SYSREPO_HEADERS is not set, the HEADERS variables contains a single
empty string:

 HEADERS = [""]

This cause an empty gcc -I option to be added:

 x86_64-linux-gnu-gcc -pthread ... -I -I/usr/include/python3.6m ...
 _sysrepo.c:22:12: fatal error: pyconfig.h: No such file or directory

Since str.split(":") does not behave as expected, add a custom function
to return an empty list when the variables SYSREPO_HEADERS or
SYSREPO_LIBRARIES are not set.

Signed-off-by: Robin Jarry <robin.jarry@6wind.com>